Exception during training: unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/home/rogia/Documents/git/side_effects/bin/train", line 35, in main
    input_path=input_path)
  File "/home/rogia/Documents/git/side_effects/side_effects/utils.py", line 136, in run_experiment
    model.train(x_train=x_train, y_train=y_train, x_valid=x_valid, y_valid=y_valid, **expt_params["train_params"])
  File "/home/rogia/Documents/git/side_effects/side_effects/models/training.py", line 38, in train
    epochs=n_epochs, callbacks=callbacks)
  File "/home/rogia/miniconda3/envs/invivo/lib/python3.6/site-packages/pytoune/framework/model.py", line 310, in fit_generator
    step=step.number)
  File "/home/rogia/miniconda3/envs/invivo/lib/python3.6/site-packages/pytoune/framework/model.py", line 325, in _fit_batch
    x, y, return_loss_tensor=True, return_pred=return_pred
  File "/home/rogia/miniconda3/envs/invivo/lib/python3.6/site-packages/pytoune/framework/model.py", line 601, in _compute_loss_and_metrics
    loss = self.loss_function(pred_y, y)
  File "/home/rogia/miniconda3/envs/invivo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rogia/Documents/git/side_effects/side_effects/external_utils/loss.py", line 37, in forward
    return binary_cross_entropy(input, target, weight=weights, reduction=None)
  File "/home/rogia/miniconda3/envs/invivo/lib/python3.6/site-packages/torch/nn/functional.py", line 1591, in binary_cross_entropy
    reduction = _Reduction.get_enum(reduction)
  File "/home/rogia/miniconda3/envs/invivo/lib/python3.6/site-packages/torch/nn/functional.py", line 30, in get_enum
    raise ValueError(reduction + " is not a valid value for reduction")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
